name: water-viz
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  
  # Core scientific python
  - numpy
  - pandas
  - zipp>=3.0

  # Geospatial libraries
  # Coordinates and CRSs
  - pyproj>=3.0
  - geopy
  - cartopy
  # Vector data
  - geopandas
  - geojson
  - pyogrio
  # Raster data
  - xarray
  - rioxarray>=0.3.0
  
  # Interactive computing
  - ipython
  - jupyterlab
  - notebook
  - tqdm

  # Data access
  - earthpy
  - earthaccess
  - dataretrieval
  - osmnx
  
  # Plotting
  # Matplotlib
  - matplotlib
  - nc-time-axis
  - descartes
  - contextily
  - seaborn
  # Holoviews
  # --- Avoid compatibility issues with bokeh and new holoviews
  - holoviews
  - hvplot
  - geoviews
  - panel
  - watchfiles
  - selenium
  - phantomjs
  - jupyter_bokeh
  # Folium
  - folium
  
  # QA
  - flake8
  - flake8-import-order
  - black
  - autopep8
  - pydocstyle
  - nbqa
